// <auto-generated />
using System;
using KomponentSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomponentSistemi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716063542_AddConnectorAndPots")]
    partial class AddConnectorAndPots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KomponentSistemi.Data.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedOfferId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("BomListId", "ComponentId")
                        .IsUnique();

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("KomponentSistemi.Data.BomList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BomLists");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mpn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrimaryValueSi")
                        .HasColumnType("REAL");

                    b.Property<string>("Rohs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SecondaryValueSi")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("PrimaryValueSi");

                    b.HasIndex("SecondaryValueSi");

                    b.HasIndex("Mpn", "Manufacturer")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kondansatör"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Direnç"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diyot"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Transistör"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Osilatör"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Regülatör"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Konnektör"
                        });
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportChanges");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportProfiles");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PriceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePartNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "Source")
                        .IsUnique();

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HotColumn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("ParameterDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            ComponentTypeId = 1,
                            DataType = "numeric",
                            DisplayName = "Kapasitans",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "capacitance",
                            Unit = "F"
                        },
                        new
                        {
                            Id = 102,
                            ComponentTypeId = 1,
                            DataType = "numeric",
                            DisplayName = "Anma Gerilimi",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 103,
                            ComponentTypeId = 1,
                            DataType = "text",
                            DisplayName = "Dielektrik",
                            IsSearchable = true,
                            Key = "dielectric"
                        },
                        new
                        {
                            Id = 104,
                            ComponentTypeId = 1,
                            DataType = "text",
                            DisplayName = "Tolerans",
                            IsSearchable = false,
                            Key = "tolerance"
                        },
                        new
                        {
                            Id = 105,
                            ComponentTypeId = 1,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 201,
                            ComponentTypeId = 2,
                            DataType = "numeric",
                            DisplayName = "Direnç",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "resistance",
                            Unit = "Ω"
                        },
                        new
                        {
                            Id = 202,
                            ComponentTypeId = 2,
                            DataType = "numeric",
                            DisplayName = "Güç",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "power",
                            Unit = "W"
                        },
                        new
                        {
                            Id = 203,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Tolerans",
                            IsSearchable = false,
                            Key = "tolerance"
                        },
                        new
                        {
                            Id = 204,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 205,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 206,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Taper (Eğri)",
                            IsSearchable = false,
                            Key = "taper"
                        },
                        new
                        {
                            Id = 207,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Tur Sayısı",
                            IsSearchable = false,
                            Key = "turns"
                        },
                        new
                        {
                            Id = 301,
                            ComponentTypeId = 3,
                            DataType = "numeric",
                            DisplayName = "Ters Gerilim (Vr)",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "reverse_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 302,
                            ComponentTypeId = 3,
                            DataType = "numeric",
                            DisplayName = "İleri Akım (If)",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "forward_current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 303,
                            ComponentTypeId = 3,
                            DataType = "numeric",
                            DisplayName = "İleri Gerilim (Vf)",
                            IsSearchable = false,
                            Key = "forward_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 304,
                            ComponentTypeId = 3,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 305,
                            ComponentTypeId = 3,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 401,
                            ComponentTypeId = 4,
                            DataType = "numeric",
                            DisplayName = "Gerilim (Vds/Vce)",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 402,
                            ComponentTypeId = 4,
                            DataType = "numeric",
                            DisplayName = "Akım",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 403,
                            ComponentTypeId = 4,
                            DataType = "numeric",
                            DisplayName = "Güç",
                            IsSearchable = false,
                            Key = "power",
                            Unit = "W"
                        },
                        new
                        {
                            Id = 404,
                            ComponentTypeId = 4,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 405,
                            ComponentTypeId = 4,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 501,
                            ComponentTypeId = 5,
                            DataType = "numeric",
                            DisplayName = "Frekans",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "frequency",
                            Unit = "Hz"
                        },
                        new
                        {
                            Id = 502,
                            ComponentTypeId = 5,
                            DataType = "numeric",
                            DisplayName = "Besleme Gerilimi",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "supply_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 503,
                            ComponentTypeId = 5,
                            DataType = "numeric",
                            DisplayName = "Frekans Toleransı",
                            IsSearchable = false,
                            Key = "frequency_tolerance",
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 504,
                            ComponentTypeId = 5,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 505,
                            ComponentTypeId = 5,
                            DataType = "text",
                            DisplayName = "Boyut",
                            IsSearchable = false,
                            Key = "size"
                        },
                        new
                        {
                            Id = 601,
                            ComponentTypeId = 6,
                            DataType = "numeric",
                            DisplayName = "Çıkış Gerilimi",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "output_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 602,
                            ComponentTypeId = 6,
                            DataType = "numeric",
                            DisplayName = "Çıkış Akımı",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "output_current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 603,
                            ComponentTypeId = 6,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 604,
                            ComponentTypeId = 6,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 701,
                            ComponentTypeId = 7,
                            DataType = "numeric",
                            DisplayName = "Pozisyon",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "positions"
                        },
                        new
                        {
                            Id = 702,
                            ComponentTypeId = 7,
                            DataType = "numeric",
                            DisplayName = "Akım",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 703,
                            ComponentTypeId = 7,
                            DataType = "numeric",
                            DisplayName = "Gerilim",
                            IsSearchable = false,
                            Key = "voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 704,
                            ComponentTypeId = 7,
                            DataType = "text",
                            DisplayName = "Aralık (Pitch)",
                            IsSearchable = false,
                            Key = "pitch"
                        },
                        new
                        {
                            Id = 705,
                            ComponentTypeId = 7,
                            DataType = "text",
                            DisplayName = "Montaj",
                            IsSearchable = false,
                            Key = "mounting"
                        });
                });

            modelBuilder.Entity("KomponentSistemi.Data.BomItem", b =>
                {
                    b.HasOne("KomponentSistemi.Data.BomList", "BomList")
                        .WithMany("Items")
                        .HasForeignKey("BomListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomponentSistemi.Data.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomList");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Component", b =>
                {
                    b.HasOne("KomponentSistemi.Data.ComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportChange", b =>
                {
                    b.HasOne("KomponentSistemi.Data.ImportBatch", "ImportBatch")
                        .WithMany("Changes")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Offer", b =>
                {
                    b.HasOne("KomponentSistemi.Data.Component", "Component")
                        .WithMany("Offers")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ParameterDefinition", b =>
                {
                    b.HasOne("KomponentSistemi.Data.ComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("KomponentSistemi.Data.BomList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Component", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportBatch", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
