// <auto-generated />
using System;
using KomponentSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomponentSistemi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260723204309_AddPackageMapAndStackpole")]
    partial class AddPackageMapAndStackpole
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("KomponentSistemi.Data.BomItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BomListId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("References")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SelectedOfferId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId");

                    b.HasIndex("BomListId", "ComponentId")
                        .IsUnique();

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("KomponentSistemi.Data.BomList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BomLists");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Component", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mpn")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("PrimaryValueSi")
                        .HasColumnType("REAL");

                    b.Property<string>("Rohs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SecondaryValueSi")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.HasIndex("PrimaryValueSi");

                    b.HasIndex("SecondaryValueSi");

                    b.HasIndex("Mpn", "Manufacturer")
                        .IsUnique();

                    b.ToTable("Components");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kondansatör"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Direnç"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Diyot"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Transistör"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Osilatör"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Regülatör"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Konnektör"
                        });
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AddedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImportBatchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrevJson")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportChanges");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DecimalSeparator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Delimiter")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Encoding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MappingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ImportProfiles");
                });

            modelBuilder.Entity("KomponentSistemi.Data.MpnProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternRegex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PowerMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TcrMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ToleranceMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueEncoding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MpnProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Manufacturer = "Vishay Sfernice",
                            Name = "Vishay Sfernice RCMS",
                            PackageMapJson = "{}",
                            PatternRegex = "^RCMS\\d{2}(?<value>[0-9R]{5})(?<tol>[A-Z])(?<tcr>[A-Z])",
                            PowerMapJson = "{}",
                            TcrMapJson = "{\"H\":50,\"E\":25,\"D\":15}",
                            ToleranceMapJson = "{\"F\":1.0,\"B\":0.1,\"A\":0.2,\"D\":0.5}",
                            ValueEncoding = "sig-zeros-R"
                        },
                        new
                        {
                            Id = 2,
                            Manufacturer = "Vishay Sfernice",
                            Name = "Vishay Sfernice RLP",
                            PackageMapJson = "{}",
                            PatternRegex = "^RLP\\d{2}(?<value>[0-9R]{5})(?<tol>[A-Z])",
                            PowerMapJson = "{}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"F\":1.0,\"J\":5.0,\"D\":0.5}",
                            ValueEncoding = "sig-zeros-R"
                        },
                        new
                        {
                            Id = 3,
                            Manufacturer = "Ohmite",
                            Name = "Ohmite 40 Serisi",
                            PackageMapJson = "{}",
                            PatternRegex = "^4(?<power>[123570])N?(?<tol>[FJ])(?<value>\\d+[RKM]\\d*|R\\d+|\\d+)(?:E)?(?:-T)?$",
                            PowerMapJson = "{\"1\":1.0,\"2\":2.0,\"3\":3.0,\"5\":5.0,\"7\":7.0,\"0\":10.0}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"F\":1.0,\"J\":5.0}",
                            ValueEncoding = "rkm"
                        },
                        new
                        {
                            Id = 4,
                            Manufacturer = "Ohmite",
                            Name = "Ohmite HSX",
                            PackageMapJson = "{}",
                            PatternRegex = "^HSX-2[WZ](?<value>\\d{4})(?<tol>[A-Z])E$",
                            PowerMapJson = "{}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"F\":1.0,\"J\":5.0}",
                            ValueEncoding = "sig-zeros-R"
                        },
                        new
                        {
                            Id = 5,
                            Manufacturer = "Vishay Sfernice",
                            Name = "Vishay Sfernice RCMT",
                            PackageMapJson = "{}",
                            PatternRegex = "^RCMT(?<power>\\d{2})(?<value>[0-9R]{5})(?<tol>[A-Z])(?<tcr>[A-Z])",
                            PowerMapJson = "{\"01\":0.063,\"02\":0.125,\"05\":0.25,\"08\":0.5,\"10\":1.0,\"20\":2.0,\"40\":4.0}",
                            TcrMapJson = "{\"H\":50,\"E\":25,\"D\":15}",
                            ToleranceMapJson = "{\"F\":1.0,\"B\":0.1,\"A\":0.2,\"D\":0.5}",
                            ValueEncoding = "sig-zeros-R"
                        },
                        new
                        {
                            Id = 6,
                            Manufacturer = "Vishay Sfernice",
                            Name = "Vishay Sfernice RCMA",
                            PackageMapJson = "{}",
                            PatternRegex = "^RCMA(?<power>\\d{2})(?<value>[0-9R]{5})(?<tol>[A-Z])(?<tcr>[A-Z])",
                            PowerMapJson = "{\"02\":0.125,\"05\":0.25,\"08\":0.5,\"10\":0.75,\"20\":1.0,\"40\":2.0}",
                            TcrMapJson = "{\"H\":50,\"E\":25,\"D\":15}",
                            ToleranceMapJson = "{\"F\":1.0,\"B\":0.1,\"A\":0.2,\"D\":0.5}",
                            ValueEncoding = "sig-zeros-R"
                        },
                        new
                        {
                            Id = 7,
                            Manufacturer = "Yageo",
                            Name = "Yageo RC",
                            PackageMapJson = "{\"0075\":\"0075\",\"0100\":\"0100\",\"0201\":\"0201\",\"0402\":\"0402\",\"0603\":\"0603\",\"0805\":\"0805\",\"1206\":\"1206\",\"1210\":\"1210\",\"1218\":\"1218\",\"2010\":\"2010\",\"2512\":\"2512\"}",
                            PatternRegex = "^RC(?<size>\\d{4})(?<tol>[BDFJ])[RKS]-(?:07|10|13|7W|7D|7N|3W)(?<value>\\d+[RKM]\\d*|R\\d+)[A-Z]?$",
                            PowerMapJson = "{}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"B\":0.1,\"D\":0.5,\"F\":1.0,\"J\":5.0}",
                            ValueEncoding = "rkm"
                        },
                        new
                        {
                            Id = 8,
                            Manufacturer = "KOA Speer",
                            Name = "KOA RK73H",
                            PackageMapJson = "{\"1F\":\"01005\",\"1H\":\"0201\",\"1E\":\"0402\",\"1J\":\"0603\",\"2A\":\"0805\",\"2B\":\"1206\",\"2E\":\"1210\",\"2H\":\"2010\",\"W2H\":\"2010\",\"3A\":\"2512\",\"W3A\":\"2512\",\"W3A2\":\"2512\"}",
                            PatternRegex = "^RK73H(?<size>W3A2|W2H|W3A|1[FHEJ]|2[ABEH]|3A)A?[TGL](?:TX|TBL|TCM|TPL|TP|TD|TE)(?<value>[0-9R]{4})(?<tol>[DF])$",
                            PowerMapJson = "{}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"D\":0.5,\"F\":1.0}",
                            ValueEncoding = "sig-zeros-R"
                        },
                        new
                        {
                            Id = 10,
                            Manufacturer = "Stackpole Electronics",
                            Name = "Stackpole SP",
                            PackageMapJson = "{}",
                            PatternRegex = "^SP3A(?<tol>[J])T(?<value>[0-9R]{4})$",
                            PowerMapJson = "{}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"J\":5.0}",
                            ValueEncoding = "rkm"
                        },
                        new
                        {
                            Id = 9,
                            Manufacturer = "Panasonic",
                            Name = "Panasonic ERJ",
                            PackageMapJson = "{}",
                            PatternRegex = "^ERJ-?[A-Z0-9]{2,4}(?<tol>[DFGJ])(?<value>[0-9R]{4})[A-Z]?$",
                            PowerMapJson = "{}",
                            TcrMapJson = "{}",
                            ToleranceMapJson = "{\"D\":0.5,\"F\":1.0,\"G\":2.0,\"J\":5.0}",
                            ValueEncoding = "sig-zeros-R"
                        });
                });

            modelBuilder.Entity("KomponentSistemi.Data.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Price")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("PriceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourcePartNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentId", "Source")
                        .IsUnique();

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ParameterDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HotColumn")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSearchable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("ParameterDefinitions");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            ComponentTypeId = 1,
                            DataType = "numeric",
                            DisplayName = "Kapasitans",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "capacitance",
                            Unit = "F"
                        },
                        new
                        {
                            Id = 102,
                            ComponentTypeId = 1,
                            DataType = "numeric",
                            DisplayName = "Anma Gerilimi",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 103,
                            ComponentTypeId = 1,
                            DataType = "text",
                            DisplayName = "Dielektrik",
                            IsSearchable = true,
                            Key = "dielectric"
                        },
                        new
                        {
                            Id = 104,
                            ComponentTypeId = 1,
                            DataType = "text",
                            DisplayName = "Tolerans",
                            IsSearchable = false,
                            Key = "tolerance"
                        },
                        new
                        {
                            Id = 105,
                            ComponentTypeId = 1,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 201,
                            ComponentTypeId = 2,
                            DataType = "numeric",
                            DisplayName = "Direnç",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "resistance",
                            Unit = "Ω"
                        },
                        new
                        {
                            Id = 202,
                            ComponentTypeId = 2,
                            DataType = "numeric",
                            DisplayName = "Güç",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "power",
                            Unit = "W"
                        },
                        new
                        {
                            Id = 203,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Tolerans",
                            IsSearchable = false,
                            Key = "tolerance"
                        },
                        new
                        {
                            Id = 204,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 205,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 206,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Taper (Eğri)",
                            IsSearchable = false,
                            Key = "taper"
                        },
                        new
                        {
                            Id = 207,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Tur Sayısı",
                            IsSearchable = false,
                            Key = "turns"
                        },
                        new
                        {
                            Id = 208,
                            ComponentTypeId = 2,
                            DataType = "numeric",
                            DisplayName = "TCR",
                            IsSearchable = false,
                            Key = "tcr",
                            Unit = "ppm/°C"
                        },
                        new
                        {
                            Id = 209,
                            ComponentTypeId = 2,
                            DataType = "text",
                            DisplayName = "Kompozisyon",
                            IsSearchable = true,
                            Key = "composition"
                        },
                        new
                        {
                            Id = 301,
                            ComponentTypeId = 3,
                            DataType = "numeric",
                            DisplayName = "Ters Gerilim (Vr)",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "reverse_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 302,
                            ComponentTypeId = 3,
                            DataType = "numeric",
                            DisplayName = "İleri Akım (If)",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "forward_current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 303,
                            ComponentTypeId = 3,
                            DataType = "numeric",
                            DisplayName = "İleri Gerilim (Vf)",
                            IsSearchable = false,
                            Key = "forward_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 304,
                            ComponentTypeId = 3,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 305,
                            ComponentTypeId = 3,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 401,
                            ComponentTypeId = 4,
                            DataType = "numeric",
                            DisplayName = "Gerilim (Vds/Vce)",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 402,
                            ComponentTypeId = 4,
                            DataType = "numeric",
                            DisplayName = "Akım",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 403,
                            ComponentTypeId = 4,
                            DataType = "numeric",
                            DisplayName = "Güç",
                            IsSearchable = false,
                            Key = "power",
                            Unit = "W"
                        },
                        new
                        {
                            Id = 404,
                            ComponentTypeId = 4,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 405,
                            ComponentTypeId = 4,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 501,
                            ComponentTypeId = 5,
                            DataType = "numeric",
                            DisplayName = "Frekans",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "frequency",
                            Unit = "Hz"
                        },
                        new
                        {
                            Id = 502,
                            ComponentTypeId = 5,
                            DataType = "numeric",
                            DisplayName = "Besleme Gerilimi",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "supply_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 503,
                            ComponentTypeId = 5,
                            DataType = "numeric",
                            DisplayName = "Frekans Toleransı",
                            IsSearchable = false,
                            Key = "frequency_tolerance",
                            Unit = "ppm"
                        },
                        new
                        {
                            Id = 504,
                            ComponentTypeId = 5,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 505,
                            ComponentTypeId = 5,
                            DataType = "text",
                            DisplayName = "Boyut",
                            IsSearchable = false,
                            Key = "size"
                        },
                        new
                        {
                            Id = 601,
                            ComponentTypeId = 6,
                            DataType = "numeric",
                            DisplayName = "Çıkış Gerilimi",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "output_voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 602,
                            ComponentTypeId = 6,
                            DataType = "numeric",
                            DisplayName = "Çıkış Akımı",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "output_current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 603,
                            ComponentTypeId = 6,
                            DataType = "text",
                            DisplayName = "Alt Tür",
                            IsSearchable = true,
                            Key = "subtype"
                        },
                        new
                        {
                            Id = 604,
                            ComponentTypeId = 6,
                            DataType = "text",
                            DisplayName = "Paket",
                            IsSearchable = true,
                            Key = "package"
                        },
                        new
                        {
                            Id = 701,
                            ComponentTypeId = 7,
                            DataType = "numeric",
                            DisplayName = "Pozisyon",
                            HotColumn = "primary",
                            IsSearchable = true,
                            Key = "positions"
                        },
                        new
                        {
                            Id = 702,
                            ComponentTypeId = 7,
                            DataType = "numeric",
                            DisplayName = "Akım",
                            HotColumn = "secondary",
                            IsSearchable = true,
                            Key = "current",
                            Unit = "A"
                        },
                        new
                        {
                            Id = 703,
                            ComponentTypeId = 7,
                            DataType = "numeric",
                            DisplayName = "Gerilim",
                            IsSearchable = false,
                            Key = "voltage",
                            Unit = "V"
                        },
                        new
                        {
                            Id = 704,
                            ComponentTypeId = 7,
                            DataType = "text",
                            DisplayName = "Aralık (Pitch)",
                            IsSearchable = false,
                            Key = "pitch"
                        },
                        new
                        {
                            Id = 705,
                            ComponentTypeId = 7,
                            DataType = "text",
                            DisplayName = "Montaj",
                            IsSearchable = false,
                            Key = "mounting"
                        });
                });

            modelBuilder.Entity("KomponentSistemi.Data.BomItem", b =>
                {
                    b.HasOne("KomponentSistemi.Data.BomList", "BomList")
                        .WithMany("Items")
                        .HasForeignKey("BomListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomponentSistemi.Data.Component", "Component")
                        .WithMany()
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BomList");

                    b.Navigation("Component");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Component", b =>
                {
                    b.HasOne("KomponentSistemi.Data.ComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportChange", b =>
                {
                    b.HasOne("KomponentSistemi.Data.ImportBatch", "ImportBatch")
                        .WithMany("Changes")
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImportBatch");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Offer", b =>
                {
                    b.HasOne("KomponentSistemi.Data.Component", "Component")
                        .WithMany("Offers")
                        .HasForeignKey("ComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ParameterDefinition", b =>
                {
                    b.HasOne("KomponentSistemi.Data.ComponentType", "ComponentType")
                        .WithMany()
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("KomponentSistemi.Data.BomList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("KomponentSistemi.Data.Component", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("KomponentSistemi.Data.ImportBatch", b =>
                {
                    b.Navigation("Changes");
                });
#pragma warning restore 612, 618
        }
    }
}
